// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: proto/news.proto

package news

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NewsParser_GetNews_FullMethodName = "/news.NewsParser/GetNews"
)

// NewsParserClient is the client API for NewsParser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NewsParserClient interface {
	GetNews(ctx context.Context, in *NewsRequest, opts ...grpc.CallOption) (*NewsResponse, error)
}

type newsParserClient struct {
	cc grpc.ClientConnInterface
}

func NewNewsParserClient(cc grpc.ClientConnInterface) NewsParserClient {
	return &newsParserClient{cc}
}

func (c *newsParserClient) GetNews(ctx context.Context, in *NewsRequest, opts ...grpc.CallOption) (*NewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewsResponse)
	err := c.cc.Invoke(ctx, NewsParser_GetNews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NewsParserServer is the server API for NewsParser service.
// All implementations must embed UnimplementedNewsParserServer
// for forward compatibility.
type NewsParserServer interface {
	GetNews(context.Context, *NewsRequest) (*NewsResponse, error)
	mustEmbedUnimplementedNewsParserServer()
}

// UnimplementedNewsParserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNewsParserServer struct{}

func (UnimplementedNewsParserServer) GetNews(context.Context, *NewsRequest) (*NewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNews not implemented")
}
func (UnimplementedNewsParserServer) mustEmbedUnimplementedNewsParserServer() {}
func (UnimplementedNewsParserServer) testEmbeddedByValue()                    {}

// UnsafeNewsParserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NewsParserServer will
// result in compilation errors.
type UnsafeNewsParserServer interface {
	mustEmbedUnimplementedNewsParserServer()
}

func RegisterNewsParserServer(s grpc.ServiceRegistrar, srv NewsParserServer) {
	// If the following call pancis, it indicates UnimplementedNewsParserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NewsParser_ServiceDesc, srv)
}

func _NewsParser_GetNews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsParserServer).GetNews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsParser_GetNews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsParserServer).GetNews(ctx, req.(*NewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NewsParser_ServiceDesc is the grpc.ServiceDesc for NewsParser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NewsParser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "news.NewsParser",
	HandlerType: (*NewsParserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNews",
			Handler:    _NewsParser_GetNews_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/news.proto",
}
